import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Menu from "./components/Menu";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({
  weight: ["100", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-main-bg text-main-color min-h-screen">
          <Navbar />
          <div className="flex">
            <div className="menuContainer w-max md:w-[200px] pl-4 py-2 border-r-2 border-soft-bg">
              <Menu />
            </div>
            <div className="contentContainer flex-1 px-4 py-2 overflow-hidden">
              {children}
            </div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
