import { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["100", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

interface Props {
  children: ReactNode;
}

const LoginLayout = ({ children }: Props) => {
  return (
    <main className="bg-main-bg text-main-color min-h-screen">{children}</main>
  );
};

export default LoginLayout;
