import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

const LoginLayout = ({ children }: Props) => {
  return (
    <main className="bg-main-bg text-main-color min-h-screen">{children}</main>
  );
};

export default LoginLayout;
