import type { Metadata } from "next";
import Footer from "../components/Footer";
import Menu from "../components/Menu";
import Navbar from "../components/Navbar";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

const DashboardLayout = ({ children }: Props) => {
  return (
    <div>
      <main className="bg-main-bg text-main-color min-h-screen">
        <Navbar />
        <div className="flex">
          <div className="menuContainer w-max md:w-[200px] pl-4 py-2 border-r-2 border-soft-bg">
            <Menu />
          </div>
          <div className="contentContainer flex-1 px-4 py-2 overflow-hidden">
            {children}
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
};

export default DashboardLayout;
